# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
      - develop
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  build-and-test:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         node: [14.x, 16.x]
     steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: yarn install
      - name: Run Tests
        run: yarn test
      - name: Build Source
        run: yarn build
      - name: Sonarcloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_OSS_TOKEN }}
          CI: true
